name: 'intro_dbt_snowflake'
version: '1.0.0'
config-version: 2

profile: 'intro_dbt_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  intro_dbt_snowflake:
    # Par défaut, tout est une vue (plus sécurisé)
    +materialized: view
    
    staging:
      # Tout ce qui est dans le dossier staging reste en vue
      +materialized: view
      
    marts:
      # Tout ce qui est dans le dossier marts devient une table physique
      +materialized: table